# Translations template for manila.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the manila project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: manila 2015.2.0.dev58\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-05-02 06:07+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: manila/context.py:58
#, python-format
msgid "Arguments dropped when creating context: %s"
msgstr ""

#: manila/service.py:281 manila/openstack/common/service.py:359
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: manila/service.py:456
msgid "Service killed that has no database entry"
msgstr ""

#: manila/api/auth.py:27
msgid ""
"manila.api.auth:ManilaKeystoneContext is deprecated. Please use "
"manila.api.middleware.auth:ManilaKeystoneContext instead."
msgstr ""

#: manila/api/auth.py:35
msgid ""
"manila.api.auth:pipeline_factory is deprecated. Please use "
"manila.api.middleware.auth:pipeline_factory instead."
msgstr ""

#: manila/api/extensions.py:223
#, python-format
msgid "osapi_share_extension is set to deprecated path: %s"
msgstr ""

#: manila/api/extensions.py:226
#, python-format
msgid ""
"Please set your flag or manila.conf settings for osapi_share_extension "
"to: %s"
msgstr ""

#: manila/api/extensions.py:235
#, python-format
msgid "Failed to load extension %(ext_factory)s: %(exc)s"
msgstr ""

#: manila/api/extensions.py:304
#, python-format
msgid "Failed to load extension %(classpath)s: %(exc)s"
msgstr ""

#: manila/api/extensions.py:329
#, python-format
msgid "Failed to load extension %(ext_name)s: %(exc)s"
msgstr ""

#: manila/api/sizelimit.py:27 manila/api/middleware/sizelimit.py:29
msgid ""
"manila.api.sizelimit:RequestBodySizeLimiter and "
"manila.api.middleware.sizelimit:RequestBodySizeLimiter are deprecated. "
"Please use oslo_middleware.sizelimit: RequestBodySizeLimiter instead."
msgstr ""

#: manila/api/openstack/__init__.py:110
#, python-format
msgid ""
"Extension %(ext_name)s: Cannot extend resource %(collection)s: No such "
"resource"
msgstr ""

#: manila/api/openstack/__init__.py:129
msgid ""
"manila.api.openstack:FaultWrapper is deprecated. Please use "
"manila.api.middleware.fault:FaultWrapper instead."
msgstr ""

#: manila/api/openstack/urlmap.py:26
msgid ""
"manila.api.openstack.urlmap:urlmap_factory is deprecated. Please use "
"manila.api.urlmap:urlmap_factory instead."
msgstr ""

#: manila/api/v1/share_networks.py:250
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create share-network "
"(%(d_consumed)d of %(d_quota)d already consumed)"
msgstr ""

#: manila/db/sqlalchemy/api.py:953
#, python-format
msgid "Change will make usage less than 0 for the following resources: %s"
msgstr ""

#: manila/network/linux/interface.py:159 manila/network/linux/interface.py:204
#, python-format
msgid "Device %s already exists"
msgstr ""

#: manila/openstack/common/loopingcall.py:87
#, python-format
msgid "task %(func_name)r run outlasted interval by %(delay).2f sec"
msgstr ""

#: manila/scheduler/host_manager.py:439
#, python-format
msgid "Share service is down. (host: %s)"
msgstr ""

#: manila/scheduler/manager.py:99
#, python-format
msgid "Failed to schedule_%(method)s: %(ex)s"
msgstr ""

#: manila/scheduler/filters/capacity_filter.py:53
#, python-format
msgid ""
"Insufficient free space for volume creation (requested / avail): "
"%(requested)s/%(available)s"
msgstr ""

#: manila/share/api.py:146
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG share "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: manila/share/api.py:155
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create share (%(d_consumed)d "
"shares already consumed)"
msgstr ""

#: manila/share/api.py:370
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create %(s_size)sG snapshot "
"(%(d_consumed)dG of %(d_quota)dG already consumed)"
msgstr ""

#: manila/share/api.py:379
#, python-format
msgid ""
"Quota exceeded for %(s_pid)s, tried to create snapshot (%(d_consumed)d "
"snapshots already consumed)"
msgstr ""

#: manila/share/manager.py:110
#, python-format
msgid ""
"Driver path %(old)s is deprecated, update your configuration to the new "
"path %(new)s"
msgstr ""

#: manila/share/manager.py:341
#, python-format
msgid ""
"Share information in exception can not be written to db because it "
"contains %s and it is not a dictionary."
msgstr ""

#: manila/share/manager.py:734
#, python-format
msgid "Server Information in exception can not be written to db : %s "
msgstr ""

#: manila/share/drivers/generic.py:290
#, python-format
msgid "Mount point '%(path)s' already exists on server '%(server)s'."
msgstr ""

#: manila/share/drivers/generic.py:316
#, python-format
msgid "Mount point '%(path)s' does not exist on server '%(server)s'."
msgstr ""

#: manila/share/drivers/generic.py:943
#, python-format
msgid "Caught error trying delete share: %(error)s, trying delete it forcibly."
msgstr ""

#: manila/share/drivers/glusterfs.py:306
#, python-format
msgid "%s is already mounted"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:591
#, python-format
msgid "Invalid request. Ignoring delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:708
#, python-format
msgid ""
"Access to %(share)s at %(export)s is already granted for %(access_to)s. "
"GlusterFS volume options might have been changed externally."
msgstr ""

#: manila/share/drivers/glusterfs_native.py:753
#, python-format
msgid ""
"Access to %(share)s at %(export)s is already denied for %(access_to)s. "
"GlusterFS volume options might have been changed externally."
msgstr ""

#: manila/share/drivers/service_instance.py:308
msgid ""
"Name for service instance security group is not provided. Skipping "
"security group step."
msgstr ""

#: manila/share/drivers/service_instance.py:343
#, python-format
msgid "Service instance %s does not exist."
msgstr ""

#: manila/share/drivers/service_instance.py:470
#, python-format
msgid ""
"No key path is available. May be non-existent key path is provided. Check"
" path_to_private_key (current value %(private_path)s) and "
"path_to_public_key (current value %(public_path)s) in manila "
"configuration file."
msgstr ""

#: manila/share/drivers/emc/plugins/isilon/isilon.py:143
#, python-format
msgid ""
"Attempted to delete NFS Share \"%s\", but the share does not appear to "
"exist."
msgstr ""

#: manila/share/drivers/emc/plugins/isilon/isilon.py:158
#, python-format
msgid ""
"Attempted to delete CIFS Share \"%s\", but the share does not appear to "
"exist."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:195
msgid ""
"Driver does not support share deletion without share network specified. "
"Return directly because there is nothing to clean"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:217
#, python-format
msgid "CIFS share %s not found. Skip the deletion"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:250
#, python-format
msgid "NFS share %s not found. Skip the deletion"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:283
#, python-format
msgid "Mount point %(path)s on %(vdm)s not found."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:286
#, python-format
msgid "Deleting mount point %(path)s on %(mover_name)s failed. Reason: %(err)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:292
msgid "Failed to find the VDM. Try to delete the file system"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:303
#, python-format
msgid "File system %s not found. Skip the deletion"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:324
#, python-format
msgid "Check point not found. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:328
#, python-format
msgid "Snapshot: %(name)s not found. Skip the deletion."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:175
#, python-format
msgid "Translated status from %(old)s to %(new)s. Message: %(info)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:824
#, python-format
msgid "Expected just one %(item)s, got %(more)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:831
#, python-format
msgid "Expected one of %(item)s, got %(child)s under %(parent)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:854
#, python-format
msgid "No parser for node type %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:881
#, python-format
msgid "Expected node type %(expected)s, not %(actual)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:891
#, python-format
msgid "Expected %(attr)s attribute on %(node)s node, but only have %(attrs)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:904
#, python-format
msgid "Invalid extra attributes %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:909
#, python-format
msgid "Unexpected node %(node)s under %(parent)s; wanted %(expected)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:919
#, python-format
msgid "Unexpected non-blank pcdata node %(node)s under %(parent)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:931
#, python-format
msgid "Expected either zero or one of %(node)s under %(parent)s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/xml_api_parser.py:951
#, python-format
msgid "Expected one of %(expected)s under %(parent)s, got %(actual)s."
msgstr ""

#: manila/share/drivers/hds/sop.py:320
#: manila/share/drivers/huawei/huawei_helper.py:403
msgid "Only ip access type allowed."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:212
#, python-format
msgid "The share was not found. share_name:%s"
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:217
msgid "The filesystem was not found."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:407
msgid "Only user access type allowed."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:413
#, python-format
msgid "Can not get share. share_name: %s"
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:419
#, python-format
msgid "Can not get access id from share. share_name: %s"
msgstr ""

#: manila/share/drivers/huawei/huawei_nas.py:150
#, python-format
msgid "Delete snapshot share id %s fs has been deleted."
msgstr ""

#: manila/share/drivers/huawei/huawei_nas.py:160
#, python-format
msgid "Can not find snapshot %s in array."
msgstr ""

#: manila/share/drivers/netapp/utils.py:46
msgid ""
"Please use NetAppDriver in the configuration file to load the driver "
"instead of directly specifying the driver module name."
msgstr ""

#: manila/share/drivers/netapp/utils.py:77
#, python-format
msgid "Invalid trace flag: %s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:556
#, python-format
msgid "No aggregates assigned to Vserver %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:1297
#, python-format
msgid "Failed to invoke EMS. %s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:479
#, python-format
msgid ""
"Could not determine share server for share being deleted: %(share)s. "
"Deletion of share record will proceed anyway. Error: %(error)s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:549
#, python-format
msgid ""
"Could not determine share server for snapshot being deleted: %(snap)s. "
"Deletion of snapshot record will proceed anyway. Error: %(error)s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:49
msgid ""
"Vserver is specified in the configuration. This is ignored when the "
"driver is managing share servers."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:236
msgid ""
"Vserver not specified for share server being deleted. Deletion of share "
"server record will proceed anyway."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:242
#, python-format
msgid ""
"Could not find Vserver for share server being deleted: %s. Deletion of "
"share server record will proceed anyway."
msgstr ""

#: manila/share/drivers/quobyte/jsonrpc.py:98
msgid ""
"Will not verify the server certificate of the API service because the CA "
"certificate is not available."
msgstr ""

#: manila/share/drivers/quobyte/jsonrpc.py:143
msgid "Could not verify server certificate of API service against CA."
msgstr ""

#: manila/share/drivers/quobyte/jsonrpc.py:163
#, python-format
msgid "Encountered error, retrying: %s"
msgstr ""

#: manila/share/drivers/quobyte/quobyte.py:158
#, python-format
msgid "No volume found for share %(project_id)s/%(name)s"
msgstr ""

