# Translations template for manila.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the manila project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: manila 2015.2.0.dev58\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-05-02 06:07+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: manila/exception.py:94
msgid "Exception in string format operation."
msgstr ""

#: manila/exception.py:96
#, python-format
msgid "%(name)s: %(value)s"
msgstr ""

#: manila/manager.py:177
#, python-format
msgid "Error during %(full_task_name)s: %(e)s"
msgstr ""

#: manila/quota.py:985
#, python-format
msgid "Failed to commit reservations %s"
msgstr ""

#: manila/quota.py:1009
#, python-format
msgid "Failed to roll back reservations %s"
msgstr ""

#: manila/service.py:237 manila/openstack/common/service.py:272
msgid "Unhandled exception"
msgstr ""

#: manila/service.py:508
msgid "Recovered model server connection!"
msgstr ""

#: manila/service.py:514
msgid "model server went away"
msgstr ""

#: manila/api/extensions.py:188
#, python-format
msgid "Exception loading extension: %s"
msgstr ""

#: manila/api/middleware/fault.py:45
#, python-format
msgid "Caught error: %s"
msgstr ""

#: manila/api/openstack/wsgi.py:470
#, python-format
msgid "Exception handling resource: %s"
msgstr ""

#: manila/api/v1/share_networks.py:89
msgid "Failed to update usages deleting share-network."
msgstr ""

#: manila/cmd/all.py:62
msgid "Failed to load osapi_share"
msgstr ""

#: manila/cmd/all.py:68
#, python-format
msgid "Failed to load %s"
msgstr ""

#: manila/db/migrations/alembic/versions/162a3e673105_manila_init.py:402
msgid "Exception while creating table."
msgstr ""

#: manila/db/migrations/alembic/versions/30cb96d995fa_add_is_public_column_for_share.py:42
msgid "Column shares.is_public not created!"
msgstr ""

#: manila/db/migrations/alembic/versions/30cb96d995fa_add_is_public_column_for_share.py:50
msgid "Column shares.is_public not dropped!"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:45
#, python-format
msgid "Column |%s| not created!"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:64
#, python-format
msgid "Table |%s| not created!"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:72
msgid "share_types.is_public column not dropped"
msgstr ""

#: manila/db/migrations/alembic/versions/ef0c02b4366_add_share_type_projects.py:78
msgid "share_type_projects table not dropped"
msgstr ""

#: manila/db/sqlalchemy/api.py:2334
#, python-format
msgid "ShareType %s deletion failed, ShareType in use."
msgstr ""

#: manila/network/linux/interface.py:175 manila/network/linux/interface.py:217
#, python-format
msgid "Failed unplugging interface '%s'"
msgstr ""

#: manila/network/linux/ovs_lib.py:49
#, python-format
msgid "Unable to execute %(cmd)s. Exception: %(exception)s"
msgstr ""

#: manila/network/neutron/api.py:167
#, python-format
msgid "Neutron error creating port on network %s"
msgstr ""

#: manila/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr ""

#: manila/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: manila/scheduler/filter_scheduler.py:227
#, python-format
msgid ""
"Error scheduling %(share_id)s from last share-service: %(last_host)s : "
"%(exc)s"
msgstr ""

#: manila/scheduler/scheduler_options.py:68
#, python-format
msgid "Could not stat scheduler options file %(filename)s: '%(e)s'"
msgstr ""

#: manila/scheduler/scheduler_options.py:78
#, python-format
msgid "Could not decode scheduler options: '%(e)s'"
msgstr ""

#: manila/scheduler/filters/capacity_filter.py:39
msgid "Free capacity not set: volume node info collection broken."
msgstr ""

#: manila/share/api.py:301
msgid "Failed to update quota for deleting share"
msgstr ""

#: manila/share/driver.py:143
#, python-format
msgid "Recovering from a failed execute. Try number %s"
msgstr ""

#: manila/share/manager.py:128
#, python-format
msgid "Failed to fetch pool name for share: %(share)s. Error: %(error)s."
msgstr ""

#: manila/share/manager.py:164
#, python-format
msgid ""
"Caught exception trying ensure share '%(s_id)s'. Exception: \n"
"%(e)s."
msgstr ""

#: manila/share/manager.py:186
#, python-format
msgid ""
"Unexpected exception during share access allow operation. Share id is "
"'%(s_id)s', access rule type is '%(ar_type)s', access rule id is "
"'%(ar_id)s', exception is '%(e)s'."
msgstr ""

#: manila/share/manager.py:295
#, python-format
msgid "Share server %s does not exist."
msgstr ""

#: manila/share/manager.py:305
msgid "Failed to get share server for share creation."
msgstr ""

#: manila/share/manager.py:326
#, python-format
msgid "Share %s failed on creation."
msgstr ""

#: manila/share/manager.py:437
#, python-format
msgid "Share can not be unmanaged: %s."
msgstr ""

#: manila/share/manager.py:451
#, python-format
msgid "Failed to update quota usages: %s."
msgstr ""

#: manila/share/manager.py:460
#, python-format
msgid "Can not remove access rules of share: %s."
msgstr ""

#: manila/share/manager.py:493
msgid "Failed to update usages deleting share"
msgstr ""

#: manila/share/manager.py:587
msgid "Failed to update usages deleting snapshot"
msgstr ""

#: manila/share/manager.py:821
#, python-format
msgid "Share server '%s' failed on deletion."
msgstr ""

#: manila/share/share_types.py:54
#, python-format
msgid "DB error: %s"
msgstr ""

#: manila/share/share_types.py:91
#, python-format
msgid "Share type %(share_type)s has invalid required extra specs: %(error)s"
msgstr ""

#: manila/share/share_types.py:177
#, python-format
msgid ""
"Default share type is not found, please check default_share_type config: "
"%s"
msgstr ""

#: manila/share/drivers/generic.py:249
#, python-format
msgid "Failed to sync mount files on server '%s'."
msgstr ""

#: manila/share/drivers/generic.py:256
#, python-format
msgid "Failed to mount all shares on server '%s'."
msgstr ""

#: manila/share/drivers/generic.py:372
#, python-format
msgid ""
"Expected only one volume in volume list with name '%(name)s', but got "
"more than one in a result - '%(result)s'."
msgstr ""

#: manila/share/drivers/generic.py:391
#, python-format
msgid ""
"Expected only one volume snapshot in list with name '%(name)s', but got "
"more than one in a result - '%(result)s'."
msgstr ""

#: manila/share/drivers/glusterfs.py:149
#: manila/share/drivers/glusterfs_native.py:621
#: manila/share/drivers/glusterfs_native.py:663
#, python-format
msgid "Error retrieving volume info: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:268
#, python-format
msgid ""
"Error in tuning GlusterFS volume to enable creation of shares of specific"
" size: %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:326
#, python-format
msgid "Could not mount the Gluster volume %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:379
#, python-format
msgid "Unable to create share %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:393
#, python-format
msgid ""
"Cannot cleanup share, %s, that errored out during its creation, but "
"exists in GlusterFS volume."
msgstr ""

#: manila/share/drivers/glusterfs.py:405
#, python-format
msgid "Unable to delete share %s"
msgstr ""

#: manila/share/drivers/glusterfs.py:459
#, python-format
msgid ""
"Error in tuning GlusterFS volume to prevent exporting the entire volume: "
"%s"
msgstr ""

#: manila/share/drivers/glusterfs.py:524
#, python-format
msgid "Error in gluster volume set: %s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:172
#, python-format
msgid "'gluster version' failed on server %(server)s with: %(message)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:187
#, python-format
msgid ""
"GlusterFS version %(version)s on server %(server)s is not supported, "
"minimum requirement: %(minvers)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:253
#, python-format
msgid "Error retrieving volume list%(hostinfo)s: %(err)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:567
#, python-format
msgid "Error creating share %(share_id)s"
msgstr ""

#: manila/share/drivers/glusterfs_native.py:600
#, python-format
msgid "Error during delete_share request for share %(share_id)s"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:568
#, python-format
msgid "Could not setup server. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:694
#, python-format
msgid "Could not find CIFS server by name: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:739
msgid "Could not get storage pool list."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/connection.py:866
#, python-format
msgid "Could not get mount point. Reason: %s."
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:90
#, python-format
msgid ""
"REQ: [%(method)s] %(url)s %(req_hdrs)s\n"
"REQ BODY: %(req_b)s\n"
"RESP: [%(code)s] %(resp_hdrs)s\n"
"RESP BODY: %(resp_b)s\n"
msgstr ""

#: manila/share/drivers/emc/plugins/vnx/helper.py:1084
#, python-format
msgid "Error running SSH command: %s"
msgstr ""

#: manila/share/drivers/ganesha/manager.py:190
#, python-format
msgid "Error while executing management command on Ganesha node %(tag)s: %(msg)s."
msgstr ""

#: manila/share/drivers/ganesha/manager.py:331
#, python-format
msgid "Invalid export database on Ganesha node %(tag)s: %(db)s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:72
#, python-format
msgid "Bad response from server: %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:164
#, python-format
msgid "Bad response from change file: %s."
msgstr ""

#: manila/share/drivers/huawei/huawei_helper.py:353
#, python-format
msgid "Read Huawei config file(%(filename)s) for Manila error: %(err)s"
msgstr ""

#: manila/share/drivers/ibm/gpfs.py:730
#, python-format
msgid "Invalid metadata %(attr)s for share %(share)s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_base.py:68
#, python-format
msgid "Could not get licenses list. %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:188
#, python-format
msgid "Vserver %s does not exist."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:199
#, python-format
msgid "Volume %s is already offline."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:228
#, python-format
msgid "CIFS server does not exist for Vserver %s."
msgstr ""

#: manila/share/drivers/netapp/dataontap/client/client_cmode.py:754
msgid "DNS exists for Vserver."
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py:138
#, python-format
msgid "Neither NFS nor CIFS is licensed on %(backend)s"
msgstr ""

#: manila/share/drivers/netapp/dataontap/cluster_mode/lib_multi_svm.py:169
msgid "Failed to create network interface(s)."
msgstr ""

#: manila/share/drivers/netapp/dataontap/protocols/cifs_cmode.py:76
#, python-format
msgid "User %s does not exist."
msgstr ""

#: manila/share/drivers/netapp/dataontap/protocols/cifs_cmode.py:78
#, python-format
msgid "Rule %s does not exist."
msgstr ""

#: manila/share/drivers/quobyte/quobyte.py:90
#, python-format
msgid "Could not connect to API: %s"
msgstr ""

#: manila/share/drivers/zfssa/zfssarest.py:237
#, python-format
msgid ""
"Error deleting share: %(share)s to pool: %(pool)s project: %(project)s "
"return code: %(ret.status)d message: %(ret.data)s."
msgstr ""

#: manila/share/drivers/zfssa/zfssashare.py:264
#, python-format
msgid "snapshot %s: has clones"
msgstr ""

